name: Manual Scrape

on:
  workflow_dispatch:

jobs:
  run-playwright:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Cache Playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: |
        pip install playwright
        playwright install --with-deps

    - name: Run Script
      env:
        ZIPCODE: ${{ vars.ZIPCODE }}
        VEHICLES_SITE1_URL: ${{ vars.VEHICLES_SITE1_URL }}
      run: python main.py
